package gohttps

import (
	"encoding/json"
	"fmt"
	"maps"
	"net/http"
)

// RFC9457Error is the data structure of an HTTP error
// that follows the [RFC 9457] specification.
// The schema is inspired by [Swagger API] specification.
//
// [RFC 9457]: https://www.rfc-editor.org/rfc/rfc9457.html
// [Swagger API]: https://swagger.io/blog/problem-details-rfc9457-api-error-handling/
type RFC9457Error struct {
	// A URI reference that identifies the problem type.
	Type string
	// The HTTP status code generated by the origin server for this occurrence of the problem.
	Status int
	// A short, human-readable summary of the problem type.
	Title string
	// A human-readable explanation specific to this occurrence of the problem.
	Detail string
	// A URI reference that identifies the specific occurrence of the problem.
	// It may or may not yield further information if dereferenced.
	Instance string
	// An API specific error code aiding the provider team understand the error based on their own potential taxonomy or registry.
	Code string
	// An array of error details to accompany a problem details response.
	Errors []ErrorDetail
	// Additional members that are specific to that problem type.
	Extensions map[string]any
}

// NewRFC9457Error creates an RFC9457Error instance with status.
func NewRFC9457Error(httpStatus int, detail string) RFC9457Error {
	return RFC9457Error{
		Type:   "about:blank",
		Status: httpStatus,
		Title:  http.StatusText(httpStatus),
		Detail: detail,
	}
}

// ErrorDetail is an object to provide explicit details on a problem towards an API consumer..
type ErrorDetail struct {
	// A granular description on the specific error related to a body property, query parameter, path parameters, and/or header.
	Detail string `json:"detail"`
	// A JSON Pointer to a specific request body property that is the source of error.
	Pointer string `json:"pointer,omitempty"`
	// The name of the query or path parameter that is the source of error.
	Parameter string `json:"parameter,omitempty"`
	// The name of the header that is the source of error.
	Header string `json:"header,omitempty"`
	// A string containing additional provider specific codes to identify the error context.
	Code string `json:"code,omitempty"`
}

// ErrAlreadyExists problem occurs when the resource being created is found to already exist on the server.
var ErrAlreadyExists = RFC9457Error{
	Type:   "https://problems-registry.smartbear.com/already-exists",
	Title:  "Already exists",
	Detail: "The resource being created already exists.",
	Status: http.StatusConflict,
	Code:   "409-01",
}

// ErrLicenseExpired occurs when the license associated with the client has expired thus rendering the service unavailable.
var ErrLicenseExpired = RFC9457Error{
	Type:   "https://problems-registry.smartbear.com/license-expired",
	Title:  "License Expired",
	Detail: "The service is unavailable as the license associated with your client or organization has expired. Please contact your account manager or representativ.",
	Status: http.StatusServiceUnavailable,
}

// ErrLicenseCancelled occurs when the license associated with the client has been cancelled thus rendering the service unavailable.
var ErrLicenseCancelled = RFC9457Error{
	Type:   "https://problems-registry.smartbear.com/license-cancelled",
	Title:  "License Cancelled",
	Detail: "The service is unavailable as the license associated with your client or organization has been cancelled. Please contact your account manager or representative.",
	Status: http.StatusServiceUnavailable,
}

// ErrNotFound occurs when the requested resource could not be found.
// Your client application tried to access a resource that does not exist (or could not be found).
// Please review how your users initiated such a request.
var ErrNotFound = RFC9457Error{
	Type:   "about:blank",
	Title:  "Not Found",
	Detail: "The requested resource was not found.",
	Status: http.StatusNotFound,
	Code:   "404-01",
}

// ErrUnauthorized occurs when the request lacks valid authentication credentials.
// Your client application tried to access a resource without providing a valid access token or authentication information.
// Please ensure that your requests include the necessary authentication credentials.
var ErrUnauthorized = RFC9457Error{
	Type:   "about:blank",
	Title:  "Unauthorized",
	Detail: "Access token not set or invalid, and the requested resource could not be returned.",
	Status: http.StatusUnauthorized,
	Code:   "401-01",
}

// ErrForbidden occurs when the requested resource (and/or operation combination) is not authorized for the requesting client (and or authorization context).
// Your client application tried to perform an operation on a resource that it’s not authorized to perform in the given context.
var ErrForbidden = RFC9457Error{
	Type:   "about:blank",
	Title:  "Forbidden",
	Detail: "The resource could not be returned as the requestor is not authorized.",
	Status: http.StatusForbidden,
	Code:   "403-01",
}

// ErrBadRequest occurs when the server cannot or will not process the request due to something that is perceived to be a client error
// (for example, malformed request syntax, invalid request message framing, or deceptive request routing).
// Your client application initiated a request that is malformed.
// Please review your client request against the defined semantics for the API.
var ErrBadRequest = RFC9457Error{
	Type:   "about:blank",
	Title:  "Bad Request",
	Detail: "The request is invalid or malformed.",
	Status: http.StatusBadRequest,
	Code:   "400-01",
}

// ErrServiceUnavailable occurs when the service requested is currently unavailable and the server is not ready to handle the request
// Your client application did everything correct. Unfortunately our API is currently unavailable.
var ErrServiceUnavailable = RFC9457Error{
	Type:   "about:blank",
	Title:  "Service Unavailable",
	Detail: "The service is currently unavailable.",
	Status: http.StatusServiceUnavailable,
	Code:   "503-01",
}

// ErrServerError occurs when the server encounters an unexpected condition that prevents it from fulfilling the request.
// Your client application did everything correct. Unfortunately our API encountered a condition that resulted in this problem.
var ErrServerError = RFC9457Error{
	Type:   "about:blank",
	Title:  "Server Error",
	Detail: "The server encountered an unexpected error.",
	Status: http.StatusInternalServerError,
	Code:   "500-01",
}

// NewMissingRequestHeaderError problem occurs when the request sent to the API is missing an expected request header.
func NewMissingRequestHeaderError(errors ...ErrorDetail) RFC9457Error {
	return RFC9457Error{
		Type:   "https://problems-registry.smartbear.com/missing-request-header",
		Title:  "Missing request header",
		Detail: "The request is missing an expected HTTP request header.",
		Status: http.StatusBadRequest,
		Code:   "400-02",
		Errors: errors,
	}
}

// NewMissingRequestParameterError occurs when the request sent to the API is missing an query or path parameter.
func NewMissingRequestParameterError(errors ...ErrorDetail) RFC9457Error {
	return RFC9457Error{
		Type:   "https://problems-registry.smartbear.com/missing-request-parameter",
		Title:  "Missing request parameter",
		Detail: "The request is missing an expected query or path parameter.",
		Status: http.StatusBadRequest,
		Code:   "400-03",
		Errors: errors,
	}
}

// NewInvalidBodyPropertyFormatError occurs when the request body contain a malformed property.
func NewInvalidBodyPropertyFormatError(errors ...ErrorDetail) RFC9457Error {
	return RFC9457Error{
		Type:   "https://problems-registry.smartbear.com/invalid-body-property-format",
		Title:  "Invalid Body Property Format",
		Detail: "The request body contains a malformed property.",
		Status: http.StatusBadRequest,
		Code:   "400-04",
		Errors: errors,
	}
}

// NewInvalidRequestParameterFormatError occurs when the request contains a malformed query or path parameter.
// Your client issued a request that contained a malformed query or path parameter.
// Please review your request parameters and compare against the shared API definition.
// Consider validating your parameters published schema prior to sending to the server.
func NewInvalidRequestParameterFormatError(errors ...ErrorDetail) RFC9457Error {
	return RFC9457Error{
		Type:   "https://problems-registry.smartbear.com/invalid-request-parameter-format",
		Title:  "Invalid Request Parameter Format",
		Detail: "The request contains a malformed query parameter.",
		Status: http.StatusBadRequest,
		Code:   "400-05",
		Errors: errors,
	}
}

// NewInvalidRequestHeaderFormatError occurs when the request contains a malformed request header.
// Your client issued a request that contained a malformed request header.
// Please review your request parameters and compare against the shared API definition when applicable.
// Consider validating your headers against the published schema or API definition metadata prior to sending to the server.
func NewInvalidRequestHeaderFormatError(errors ...ErrorDetail) RFC9457Error {
	return RFC9457Error{
		Type:   "https://problems-registry.smartbear.com/invalid-request-header-format",
		Title:  "Invalid Request Header Format",
		Detail: "The request contains a malformed request header parameter.",
		Status: http.StatusBadRequest,
		Code:   "400-06",
		Errors: errors,
	}
}

// NewInvalidBodyPropertyValueError occurs when the request body contains a invalid property value.
func NewInvalidBodyPropertyValueError(errors ...ErrorDetail) RFC9457Error {
	return RFC9457Error{
		Type:   "https://problems-registry.smartbear.com/invalid-body-property-value",
		Title:  "Invalid Body Property Value",
		Detail: "The request body contains an invalid body property value.",
		Status: http.StatusBadRequest,
		Code:   "400-07",
		Errors: errors,
	}
}

// NewInvalidRequestParameterValueError occurs when the request contains a invalid query or path parameter value.
func NewInvalidRequestParameterValueError(errors ...ErrorDetail) RFC9457Error {
	return RFC9457Error{
		Type:   "https://problems-registry.smartbear.com/invalid-request-parameter-value",
		Title:  "Invalid Request Parameter Value",
		Detail: "The request body contains an invalid request parameter value.",
		Status: http.StatusBadRequest,
		Code:   "400-08",
		Errors: errors,
	}
}

// NewMissingBodyPropertyError creates a missing body property error.
// This problem occurs when the request sent to the API is missing an expected body property.
func NewMissingBodyPropertyError(errors ...ErrorDetail) RFC9457Error {
	return RFC9457Error{
		Type:   "https://problems-registry.smartbear.com/missing-body-property",
		Title:  "Missing body property",
		Detail: "The request is missing an expected body property.",
		Status: http.StatusBadRequest,
		Code:   "400-09",
		Errors: errors,
	}
}

// NewBusinessRuleViolationError occurs when the request is deemed unprocessable.
// Your client issued a request that failed business rule validation.
// Please review your request to determine if you can remain within appropriate business rules.
// Consider validating your request against available metadata (e.g. schemas) prior to sending to the server.
func NewBusinessRuleViolationError(errors ...ErrorDetail) RFC9457Error {
	return RFC9457Error{
		Type:   "https://problems-registry.smartbear.com/business-rule-violation",
		Title:  "Business Rule Violation",
		Detail: "The request body is invalid and not meeting business rules.",
		Status: http.StatusUnprocessableEntity,
		Code:   "422-01",
		Errors: errors,
	}
}

// NewValidationError occurs when the request is deemed unprocessable.
func NewValidationError(errors ...ErrorDetail) RFC9457Error {
	return RFC9457Error{
		Type:   "https://problems-registry.smartbear.com/validation-error",
		Title:  "Validation Error",
		Detail: "The request is not valid.",
		Status: http.StatusUnprocessableEntity,
		Code:   "422-02",
		Errors: errors,
	}
}

// Error implements the error interface for RFC9457Error.
func (e RFC9457Error) Error() string {
	return fmt.Sprintf("%s, type=%s, detail=%s, status=%d, instance=%s, extensions=%v",
		e.Title, e.Type, e.Detail, e.Status, e.Instance, e.Extensions)
}

// MarshalJSON implements the json.Marshaler interface.
func (e RFC9457Error) MarshalJSON() ([]byte, error) {
	result := maps.Clone(e.Extensions)

	if e.Type != "" {
		result["type"] = e.Type
	}

	if e.Status > 0 {
		result["status"] = e.Status
	}

	if e.Title != "" {
		result["title"] = e.Title
	}

	if e.Detail != "" {
		result["detail"] = e.Detail
	}

	if e.Instance != "" {
		result["instance"] = e.Instance
	}

	if e.Code != "" {
		result["code"] = e.Code
	}

	if e.Errors != nil {
		result["errors"] = e.Errors
	}

	return json.Marshal(result)
}

// UnmarshalJSON implements the json.Unmarshaler interface.
func (e *RFC9457Error) UnmarshalJSON(data []byte) error { //nolint:revive,cyclop
	rawError := map[string]json.RawMessage{}

	err := json.Unmarshal(data, &rawError)
	if err != nil {
		return err
	}

	e.Extensions = map[string]any{}

	for key, rawValue := range rawError {
		if len(rawValue) == 0 {
			continue
		}

		switch key {
		case "type":
			err := json.Unmarshal(rawValue, &e.Type)
			if err != nil {
				return fmt.Errorf("failed to decode error type: %w", err)
			}
		case "status":
			err := json.Unmarshal(rawValue, &e.Status)
			if err != nil {
				return fmt.Errorf("failed to decode http error status: %w", err)
			}
		case "title":
			err := json.Unmarshal(rawValue, &e.Title)
			if err != nil {
				return fmt.Errorf("failed to decode error title: %w", err)
			}
		case "detail":
			err := json.Unmarshal(rawValue, &e.Detail)
			if err != nil {
				return fmt.Errorf("failed to decode error detail: %w", err)
			}
		case "instance":
			err := json.Unmarshal(rawValue, &e.Instance)
			if err != nil {
				return fmt.Errorf("failed to decode error instance: %w", err)
			}
		case "code":
			err := json.Unmarshal(rawValue, &e.Code)
			if err != nil {
				return fmt.Errorf("failed to decode error code: %w", err)
			}
		case "errors":
			err := json.Unmarshal(rawValue, &e.Errors)
			if err != nil {
				return fmt.Errorf("failed to decode error details: %w", err)
			}
		default:
			e.Extensions[key] = rawValue
		}
	}

	return nil
}
