package gohttps

import (
	"encoding/json"
	"fmt"
	"maps"
	"net/http"
)

// RFC9457Error is the data structure of an HTTP error
// that follows the [RFC 9457] specification.
// The schema is inspired by [Swagger API] specification.
//
// [RFC 9457]: https://www.rfc-editor.org/rfc/rfc9457.html
// [Swagger API]: https://swagger.io/blog/problem-details-rfc9457-api-error-handling/
type RFC9457Error struct {
	// A URI reference that identifies the problem type.
	Type string
	// The HTTP status code generated by the origin server for this occurrence of the problem.
	Status int
	// A short, human-readable summary of the problem type.
	Title string
	// A human-readable explanation specific to this occurrence of the problem.
	Detail string
	// A URI reference that identifies the specific occurrence of the problem.
	// It may or may not yield further information if dereferenced.
	Instance string
	// An API specific error code aiding the provider team understand the error based on their own potential taxonomy or registry.
	Code string
	// An array of error details to accompany a problem details response.
	Errors []ErrorDetail
	// Additional members that are specific to that problem type.
	Extensions map[string]any
}

// NewRFC9457Error creates an RFC9457Error instance with status.
func NewRFC9457Error(httpStatus int, detail string) RFC9457Error {
	return RFC9457Error{
		Status: httpStatus,
		Title:  http.StatusText(httpStatus),
		Detail: detail,
	}
}

// Error implements the error interface for RFC9457Error.
func (e RFC9457Error) Error() string {
	return fmt.Sprintf("%s, type=%s, detail=%s, status=%d, instance=%s, extensions=%v",
		e.Title, e.Type, e.Detail, e.Status, e.Instance, e.Extensions)
}

// MarshalJSON implements the json.Marshaler interface.
func (e RFC9457Error) MarshalJSON() ([]byte, error) {
	result := maps.Clone(e.Extensions)

	if e.Type != "" {
		result["type"] = e.Type
	}

	if e.Status > 0 {
		result["status"] = e.Status
	}

	if e.Title != "" {
		result["title"] = e.Title
	}

	if e.Detail != "" {
		result["detail"] = e.Detail
	}

	if e.Instance != "" {
		result["instance"] = e.Instance
	}

	if e.Code != "" {
		result["code"] = e.Code
	}

	if e.Errors != nil {
		result["errors"] = e.Errors
	}

	return json.Marshal(result)
}

// UnmarshalJSON implements the json.Unmarshaler interface.
func (e *RFC9457Error) UnmarshalJSON(data []byte) error { //nolint:revive,cyclop
	rawError := map[string]json.RawMessage{}

	err := json.Unmarshal(data, &rawError)
	if err != nil {
		return err
	}

	e.Extensions = map[string]any{}

	for key, rawValue := range rawError {
		if len(rawValue) == 0 {
			continue
		}

		switch key {
		case "type":
			err := json.Unmarshal(rawValue, &e.Type)
			if err != nil {
				return fmt.Errorf("failed to decode error type: %w", err)
			}
		case "status":
			err := json.Unmarshal(rawValue, &e.Status)
			if err != nil {
				return fmt.Errorf("failed to decode http error status: %w", err)
			}
		case "title":
			err := json.Unmarshal(rawValue, &e.Title)
			if err != nil {
				return fmt.Errorf("failed to decode error title: %w", err)
			}
		case "detail":
			err := json.Unmarshal(rawValue, &e.Detail)
			if err != nil {
				return fmt.Errorf("failed to decode error detail: %w", err)
			}
		case "instance":
			err := json.Unmarshal(rawValue, &e.Instance)
			if err != nil {
				return fmt.Errorf("failed to decode error instance: %w", err)
			}
		case "code":
			err := json.Unmarshal(rawValue, &e.Code)
			if err != nil {
				return fmt.Errorf("failed to decode error code: %w", err)
			}
		case "errors":
			err := json.Unmarshal(rawValue, &e.Errors)
			if err != nil {
				return fmt.Errorf("failed to decode error details: %w", err)
			}
		default:
			e.Extensions[key] = rawValue
		}
	}

	return nil
}

// ErrorDetail is an object to provide explicit details on a problem towards an API consumer..
type ErrorDetail struct {
	// A granular description on the specific error related to a body property, query parameter, path parameters, and/or header.
	Detail string `json:"detail"`
	// A JSON Pointer to a specific request body property that is the source of error.
	Pointer string `json:"pointer,omitempty"`
	// The name of the query or path parameter that is the source of error.
	Parameter string `json:"parameter,omitempty"`
	// The name of the header that is the source of error.
	Header string `json:"header,omitempty"`
	// A string containing additional provider specific codes to identify the error context.
	Code string `json:"code,omitempty"`
}
